language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r ./requirements/requirements-test.txt --use-mirrors
script:
  - cd src && python manage.py test --settings=pyweb101.settings_test

